let ranking = [{
    'nombremascota': 'Koko',
    'fechaentrada': '21/05/26',
    'fechasalida': '21/06/26',
    'padecimientos': 'Falta de vitaminas',
    'cuidadosespeciales': 'Vitaminita C89',
    'valoracion': '3/3',
    'comportamiento': 'Agresivo',
}, {
    'nombremascota': 'AChelo',
    'fechaentrada': '18/08/26',
    'fechasalida': '07/09/26',
    'padecimientos': 'Falta de vida',
    'cuidadosespeciales': 'Amor',
    'valoracion': '1/3',
    'comportamiento': 'Tranquilo',
}, {
    'nombremascota': 'Manrueco',
    'fechaentrada': '18/08/26',
    'fechasalida': '07/09/26',
    'padecimientos': 'No le gusta comer',
    'cuidadosespeciales': 'Darle un pedazo de queso en la comida',
    'valoracion': '2/3',
    'comportamiento': 'Tranquilo',
}, {
    'nombremascota': 'ManChego',
    'fechaentrada': '18/08/26',
    'fechasalida': '07/09/26',
    'padecimientos': 'Altas cantidades de estres',
    'cuidadosespeciales': 'Amor',
    'valoracion': '2/3',
    'comportamiento': 'Estresado',
}, {
    'nombremascota': 'Kiko',
    'fechaentrada': '01/12/27',
    'fechasalida': '31/12/27',
    'padecimientos': 'No le gusta moverse',
    'cuidadosespeciales': 'Ponerlo en la caminadora',
    'valoracion': '1/3',
    'comportamiento': 'Tranquilo',
}, {
    'nombremascota': 'Juan',
    'fechaentrada': '01/01/26',
    'fechasalida': '31/12/27',
    'padecimientos': 'No le gusta su hogar',
    'cuidadosespeciales': 'Buscando hogar',
    'valoracion': '3/3',
    'comportamiento': 'Perezoso',
}, {
    'nombremascota': 'Pitagoras',
    'fechaentrada': '18/02/26',
    'fechasalida': '18/03/26',
    'padecimientos': 'No le gusta el agua',
    'cuidadosespeciales': 'Darle agua con sabor',
    'valoracion': '1/3',
    'comportamiento': 'Tranquilo',
}];